
import React from 'react';
import {
  StyleSheet
} from 'react-native';
import {redish, blueish, yellowish, lightGrey, darkGrey} from './Components/Constants'

const styles = StyleSheet.create({
  container: {
    // display: 'flex',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: redish,
  },
  container2: {
    // display: 'flex',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'black',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: 'black',
    marginBottom: 5,
  },
  navigationBar: {
    margin: 5,
    paddingTop: 15,
    flexDirection: 'row',
    backgroundColor: 'blue',
    position: 'absolute',
    paddingTop: 0,
    bottom: 5,
    height: 64,
    right: 0,
    left: 0,
    borderBottomWidth: 0.5,
    borderBottomColor: 'white',
  },
  navButton: {
    color: 'white',
    textAlign: 'center',
    margin: 15,
    width: '17%',
    // flexBasis: 'auto',
  },
  button: {
    backgroundColor: 'blue',
    color: 'white',
    height: 30,
    lineHeight: 30,
    marginTop: 10,
    textAlign: 'center',
    width: 250
  },
  input: {
    color: yellowish,
    fontFamily:'Ghoulish Intent',
    fontSize: 20,
    backgroundColor: 'black',
    margin: 'auto',
    padding: 10,
    textAlign: 'center',
    borderColor: 'black',
    borderWidth: 3,
    borderRadius: 18,
    height: 35,
    width: 250,
  },
  mapcontainer: {
    height: 555,
    width: 375,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'flex-end',
    alignItems: 'center',
    display: 'flex'
  },
  mapcontainerNoNav: {
    height: 600,
    width: 375,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'flex-end',
    alignItems: 'center',
    display: 'flex'
  },
  map: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    display: 'flex',
    zIndex: 0,

  },
    icon: {
    width: 26,
    height: 26,
  },
  createRoute: {
    height: 50,
    width: 100,
    backgroundColor: '#b0c4de',
    zIndex: 1,
    // position: 'absolute',
    // top: 30,
    // right: 50,
  },
  filter: {
    zIndex: 1,
    height: 50,
    width: 100 ,
    backgroundColor: 'blue',
    position: 'absolute',
    top: 30,
    right: 50,
  },
  filterHolder: {
    zIndex: 1,
    height: 50,
    width: 100 ,
    backgroundColor: 'blue',
    position: 'absolute',
    top: 60,
    right: 50,
  },
   filterInput: {
    color: yellowish,
    fontFamily:'Ghoulish Intent',
    fontSize: 20,
    backgroundColor: 'black',
    margin: 'auto',
    padding: 10,
    textAlign: 'center',
    borderColor: 'black',
    borderWidth: 3,
    borderRadius: 18,
    height: 35,
    width: 50,
  },
  btnHolder: {
    flex: 1,
    flexDirection: 'row',
    zIndex: 1,
    height: 50,
    width: '100%',
    // backgroundColor: 'orange',
    position: 'absolute',
    top: 20,
    alignItems: 'center',
    justifyContent: 'space-around'
  },
  btnHolderVert: {
    // borderWidth: 3,
    // borderColor: 'red',
    flex: 1,
    flexDirection: 'row',
    zIndex: 1,
    height: 50,
    width: 100,
    // backgroundColor: 'orange',
    position: 'absolute',
    left: 25,
    top: 20,
    alignItems: 'flex-start',
    justifyContent: 'space-around'
  },
  btnHolderLow: {
    flex: 1,
    flexDirection: 'row',
    zIndex: 1,
    height: 20,
    width: '100%',
    // backgroundColor: 'orange',
    position: 'absolute',
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'space-around'
  },
  genRoute: {
    zIndex: 1,
    height: 50,
    width: 100 ,
    backgroundColor: 'blue',
    position: 'absolute',
    top: 65,
    left: 50,
  },
  incrementRouteNum: {
    zIndex: 1,
    height: 50,
    width: 100 ,
    backgroundColor: 'blue',
    position: 'absolute',
    top: 100,
    left: 50,
  },
  timer: {
    height: 50,
    width: 100,
    backgroundColor: '#b0c4de',
    zIndex: 1,
    position: 'absolute',
    top: 30,
    right: 50,
  },
   startStop: {
    zIndex: 1,
    height: 50,
    width: 100 ,
    backgroundColor: 'blue',
    position: 'absolute',
    top: 30,
    left: 50,
  },
  viewRoute: {
    zIndex: 1,
    height: 50,
    width: 100 ,
    backgroundColor: 'orange',
    position: 'absolute',
    top: 30,
    left: 50,
  },
    finalTime: {
    zIndex: 1,
    height: 50,
    width: 100 ,
    backgroundColor: 'blue',
    position: 'absolute',
    top: 30,
    left: 50,
  },
   submitRoute: {
    zIndex: 1,
    height: 50,
    width: 100 ,
    backgroundColor: 'green',
    position: 'absolute',
    bottom: 30,
    left: 50,
  },
  replayRoute: {
    zIndex: 1,
    height: 50,
    width: 100 ,
    backgroundColor: 'orange',
    position: 'absolute',
    bottom: 30,
    right: 50,
  },
  finalDistance: {
    height: 50,
    width: 100,
    backgroundColor: '#b0c4de',
    zIndex: 1,
    position: 'absolute',
    top: 30,
    right: 50,
  },
    replaySpeed1: {
    height: 50,
    width: 100,
    backgroundColor: '#b0c4de',
    zIndex: 1,
    position: 'absolute',
    top: 30,
    right: 50,
  },
  replaySpeed2: {
    height: 50,
    width: 100,
    backgroundColor: '#b0c4de',
    zIndex: 1,
    position: 'absolute',
    top: 80,
    right: 50,
  },
  replaySpeed4: {
    height: 50,
    width: 100,
    backgroundColor: '#b0c4de',
    zIndex: 1,
    position: 'absolute',
    top: 130,
    right: 50,
  },
  replaySpeed10: {
    height: 50,
    width: 100,
    backgroundColor: '#b0c4de',
    zIndex: 1,
    position: 'absolute',
    top: 180,
    right: 50,
  },
   changeView: {
    zIndex: 1,
    height: 50,
    width: 100 ,
    backgroundColor: 'orange',
    position: 'absolute',
    top: 30,
    left: 50,
  },
  changeTypeHeartRate: {
    zIndex: 1,
    height: 50,
    width: 100 ,
    backgroundColor: 'green',
    position: 'absolute',
    top: 100,
    left: 10,
  },
  changeTypeSpeed: {
    zIndex: 1,
    height: 50,
    width: 100 ,
    backgroundColor: 'green',
    position: 'absolute',
    top: 100,
    left: 100,
  },
  changeTypeRegular: {
    zIndex: 1,
    height: 50,
    width: 100 ,
    backgroundColor: 'green',
    position: 'absolute',
    top: 100,
    left: 190,
  },
   replayRoute: {
    zIndex: 1,
    height: 50,
    width: 80 ,
    backgroundColor: 'yellow',
    position: 'absolute',
    top: 100,
    right: 10,
  },
  homeButton: {
    zIndex: 1,
    height: 50,
    width: 80 ,
    backgroundColor: 'red',
    position: 'absolute',
    bottom: 200,
    left: 200,
  },
  replayTimer: {
    zIndex: 1,
    height: 50,
    width: 80 ,
    backgroundColor: 'purple',
    position: 'absolute',
    top: 100,
    right: 100,
  },
   popUpMessage: {
    zIndex: 1,
    height: 50,
    width: 80 ,
    backgroundColor: 'purple',
    position: 'absolute',
    top: 100,
    right: 100,
  },
  userHeader: {
    display: 'flex',
    backgroundColor: 'orange',
    height: 200,
    width: 500,
    justifyContent: 'center',

  },

  userCity: {
    justifyContent: 'center'
  },
  userName: {
    alignItems: 'center'
  },
  userStats: {
    margin: 2
  },
  scrollListHeader: {
    fontFamily: 'Magnum',
    fontWeight: '900',
    width: '33%',
    height: 35,
    color: yellowish,
    textAlign: 'center',
    fontSize: 20,
    padding: 3,
    paddingTop: 7,
    backgroundColor: 'black',
    textShadowColor: 'black',
    textShadowOffset: {width: 1, height: 1},
    textShadowRadius: 1,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: yellowish
  },
  scrollListHeader2: {
    fontFamily: 'Magnum',
    fontWeight: '900',
    width: '48%',
    height: 35,
    color: yellowish,
    textAlign: 'center',
    fontSize: 25,
    padding: 3,
    paddingTop: 7,
    backgroundColor: 'black',
    textShadowColor: 'black',
    textShadowOffset: {width: 1, height: 1},
    textShadowRadius: 1,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: yellowish
  },
  scrollListRow: {
    flex: 0,
    flexDirection: 'row',
    justifyContent: 'space-around',
    borderRadius: 15,
    backgroundColor: 'white',
  },
  scrollListRowOdd: {
    flex: 0,
    flexDirection: 'row',
    justifyContent: 'space-around',
    // backgroundColor: '#999999',
    borderWidth: 1,
    borderColor: yellowish,
  },
  scrollListRowEven: {
    flex: 0,
    flexDirection: 'row',
    justifyContent: 'space-around',
    // backgroundColor: 'white',
    borderWidth: 1,
    borderColor: yellowish,
  },
  scrollListItem: {
    textAlign: 'center',
    fontFamily: 'Ghoulish Intent',
    fontSize: 25,
    color: yellowish,
    backgroundColor: 'transparent',
    width: '30%',
    textShadowColor: 'black',
    textShadowOffset: {width: 3, height: 3},
    textShadowRadius: 3,
  },
  scrollListItem2: {
    textAlign: 'center',
    fontFamily: 'Ghoulish Intent',
    fontSize: 30,
    color: yellowish,
    backgroundColor: 'transparent',
    width: '48%'
  },
  genRouteStatus:{
    zIndex: 1,
    height: 50,
    width: 100 ,
    backgroundColor: 'blue',
    position: 'absolute',
    top: 400,
    left: 50,
  },
  setStartEnd: {
    zIndex: 1,
    height: 50,
    width: 100 ,
    backgroundColor: 'blue',
    position: 'absolute',
    top: 200,
    left: 50,
  },
  scrollListItemOppNameOdd: {
    alignItems: 'center',
    width: '48%',
    backgroundColor: redish,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: yellowish,
    margin: 1,
  },
  scrollListItemOppNameEven: {
    alignItems: 'center',
    width: '48%',
    backgroundColor: blueish,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: yellowish,
    margin: 1,
  },
  scrollListItemOppName: {
    paddingTop: 3,
    textAlign: 'center',
    fontFamily: 'Magnum',
    fontSize: 25,
    color: yellowish,
    width: '48%',
    backgroundColor: 'transparent',
    textShadowColor: 'black',
    textShadowRadius: 1,
    textShadowOffset: {width : 1, height: 1}
  },
    dot: {
     width: 10,
     height: 10,
     borderRadius: 5,
     backgroundColor: redish
   },
   dotBlack: {
   width: 10,
   height: 10,
   borderRadius: 5,
   backgroundColor: 'black'
   },
   dotGrey: {
     width: 10,
     height: 10,
     borderRadius: 5,
     backgroundColor: lightGrey
   },

  });

export default styles
